psh: add documentation of `date` command
phoenix-rtos/phoenix-rtos-doc pull request #110
Opened 2022-03-04 13:53 UTC by niewim19

JIRA: PD-249

2022-03-08 15:24 UTC, damianloew requested changes
I think it's fine, but I would leave here some info about printed format, for example describing what does 70 mean here.

2022-03-08 15:24 UTC, damianloew commented on utils/psh.md
> +* [`cat`](psh-applets/date.md)        - print/set the system date
Small typo, cat -> date

2022-03-08 15:42 UTC, damianloew submitted a review, later dismissed

2022-05-13 10:15 UTC, agkaminski approved these changes

2022-05-13 10:16 UTC, merged