libc: complete documentation for stdio functions
phoenix-rtos/phoenix-rtos-doc pull request #134
Opened 2023-01-05 19:00 UTC by damianloew

DONE: PD-331

2023-01-13 13:51 UTC, niewim19 requested changes
Common additional space in `Synopsis` parts. Other than that good

2023-01-13 13:51 UTC, niewim19 commented on libc/functions/f/feof.impl.md
> +` int feof(FILE *stream);`</br>
```suggestion
`int feof(FILE *stream);`</br>
```

2023-01-13 13:51 UTC, niewim19 commented on libc/functions/f/ferror.impl.md
> +` int ferror(FILE *stream);`</br>
```suggestion
`int ferror(FILE *stream);`</br>
```

2023-01-13 13:51 UTC, niewim19 commented on libc/functions/p/pclose.part-impl.md
> +` int pclose(FILE *stream);`</br>
```suggestion
`int pclose(FILE *stream);`</br>
```

2023-01-13 13:51 UTC, niewim19 commented on libc/functions/p/popen.part-impl.md
> +` FILE *popen(const char *command, const char *mode);`</br>
```suggestion
`FILE *popen(const char *command, const char *mode);`</br>
```

2023-01-13 14:45 UTC, damianloew commented
> Common additional space in `Synopsis` parts. Other than that good

Thanks, corrected.

2023-01-16 11:44 UTC, niewim19 approved these changes
LGTM

2023-01-16 12:22 UTC, merged