doc: correct markdown issues
phoenix-rtos/phoenix-rtos-doc pull request #154
Opened 2023-07-06 14:25 UTC by maska989

JIRA: CI-290

2023-08-11 14:46 UTC, mateusz-bloch approved these changes
I would merge this as it stands. It's true that LanguageTool might flag some inconsistencies, but this PR should focus only on markdownlint and misspell.

2023-08-11 15:58 UTC, damianloew requested changes
Big thanks fro those changes, our documentation is going to be much decent.A few remarks left.

2023-08-11 15:58 UTC, damianloew commented on ports/mbedtls.md
> +```Bash
```suggestion
```plaintext
```

2023-08-11 15:58 UTC, damianloew commented on quickstart/armv7m4-stm32l4x6-nucleo.md
> +```bash
```suggestion
```plaintext
```

2023-08-11 15:58 UTC, damianloew commented on quickstart/armv7m7-imxrt106x-evk.md
> +```bash
```suggestion
```plaintext
```

2023-08-11 15:58 UTC, damianloew commented on quickstart/armv7m7-imxrt117x-evk.md
> +```bash
```suggestion
```plaintext
```

2023-08-11 15:58 UTC, damianloew commented on quickstart/riscv64-generic-qemu.md
> +```bash
```suggestion
```plaintext
```

2023-08-11 15:58 UTC, damianloew commented on tests/README.md
> +If you tried to run this test case on a different target not listed in this YAML configuration, the test runner
1st conditional
```suggestion
If you try to run this test case on a different target not listed in this YAML configuration, the test runner
```

2023-08-16 15:03 UTC, damianloew approved these changes
LGTM

2023-08-16 15:04 UTC, merged