languagetool: disabled specific rules
phoenix-rtos/phoenix-rtos-doc pull request #158
Opened 2023-08-09 11:40 UTC by mateusz-bloch

2023-08-22 13:40 UTC, damianloew requested changes
As we discussed let's leave LC_AFTER_PERIOD and DATE_WEEKDAY_WITHOUT_YEAR

2023-08-23 08:03 UTC, nalajcie commented
small note: please use imperative mood in commit messages (`disable` instead od `disabled`).

Worth considering: most of the issues stem from markdown code blocks being checked as native text - the ideal solution would be to make languagetool NOT check the code blocks at all (that way we could keep the rules enabled for native text). From quick research - I haven't found out-of-the box solution for it, but it probably could be done by LanguageTool API (so, writing our custom languagetool-based checker) and using it in CI.

2023-09-29 11:50 UTC, damianloew reviewed
Please correct commit messages and leave the mentioned comment - IMHO we can merge it for now.

2023-09-29 11:50 UTC, damianloew commented on .github/workflows/lint.yml
> +          disabled_rules: "ENGLISH_WORD_REPEAT_RULE,RB_RB_COMMA[3],REP_PASSIVE_VOICE[6],AI[1],ID_CASING[2],ENGLISH_WORD_REPEAT_BEGINNING_RULE,EN_UNPAIRED_BRACKETS"
```suggestion
          disabled_rules: 
# TODO: make languagetool not check the code blocks and enable back most of rules mentioned below       "ENGLISH_WORD_REPEAT_RULE,RB_RB_COMMA[3],REP_PASSIVE_VOICE[6],AI[1],ID_CASING[2],ENGLISH_WORD_REPEAT_BEGINNING_RULE,EN_UNPAIRED_BRACKETS"
```

2023-10-02 09:36 UTC, damianloew commented on .github/workflows/lint.yml
> +          # TODO: make languagetool not check the code blocks and enable back most of rules mentioned below:
```suggestion
          # TODO: make languagetool not check the code blocks and enable back rules mentioned below:
```

2023-10-02 10:01 UTC, damianloew approved these changes
LGTM

2023-10-02 10:01 UTC, merged