K arkadiusz/docs update
phoenix-rtos/phoenix-rtos-doc pull request #173
Opened 2024-02-29 19:33 UTC by KArkadiusz

2024-03-01 08:36 UTC, nalajcie commented
small nitpick: the commit message is not completely valid - we're keeping our docs in Markdown, just using native MD syntax for embedding images (reStructuredText is a completely different format and image embedding is done there differently).

2024-03-04 18:11 UTC, damianloew requested changes

2024-03-04 18:11 UTC, damianloew commented on libc/functions/p/printf.part-impl.md
> +# printf
File to remove. Please look for similar ones.

2024-03-04 18:13 UTC, damianloew reviewed
`doc: adapt headers of libc functions to MD format` - it's not adapting to md format - it's just correcting the header in those files.

2024-03-07 10:38 UTC, damianloew approved these changes
Changed only commit messages in the last force push, LGTM

2024-03-07 10:40 UTC, merged