psh: update psh-applets
phoenix-rtos/phoenix-rtos-doc pull request #180
Opened 2024-03-07 15:01 UTC by mateusz-bloch

JIRA: CI-426

2024-03-07 16:16 UTC, mateusz-bloch commented on utils/psh-applets/hm.md
> +
???

2024-03-12 12:07 UTC, damianloew requested changes
Thanks for those descriptions! I think it would be good to leave some note on `psh` page in the `Applets` chapter. Sth like:

`In psh, each command or set of commands is a separate applet. The basic usage of most applets is compatible with POSIX requirements. For example, `ls` works like the `ls` user command on Ubuntu (or other Linux distribution), except for particular arguments that are not supported. The Phoenix shell is constantly under development so the exact behavior may differ a little bit, especially since new capabilities may become available. Here's a list of the provided applets:`

2024-03-12 12:10 UTC, damianloew reviewed
@gerard5, @agkaminski could you take a quick look? Maybe you see some issues when reading those descriptions.

2024-03-18 12:11 UTC, agkaminski submitted a review, later dismissed

2024-03-18 16:03 UTC, damianloew commented on utils/psh-applets/wget.md
> +# wget
Please also change the headers of the existing descriptions to lowercase for consistency. Otherwise LGTM

2024-03-18 17:22 UTC, damianloew approved these changes
Thanks, LGTM

2024-03-18 17:22 UTC, merged